[book]
title = "The Terra RFC Book"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/terrapkg/rfcs/"
site-url = "rfcs/"
edit-url-template = "https://github.com/terrapkg/rfcs/edit/main/{path}"
admonitions = true

[output.html.playground]
runnable = false

[build]
extra-watch-dirs = ["src"]
